[Icon Theme]
Name=Breeze
Comment=Breeze by the KDE VDG

Directories=actions/16,actions/22,actions/24,actions/32,mimetypes/16,mimetypes/22

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Fixed
